BUGFIX: SubscriptionDetachedStatusTest::projectionIsDetachedIfConfigurationIsRemoved
> InvalidArgumentException: Subscriber with the subscription id "Vendor.Package:FakeProjection" not found.

The subscriber is detached, so the state is not calculate-able at this point!